//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QrCodeDetector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatchDirectoryLocation {
            get {
                return ((string)(this["WatchDirectoryLocation"]));
            }
            set {
                this["WatchDirectoryLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QrCodeDetectorFormLocationX {
            get {
                return ((int)(this["QrCodeDetectorFormLocationX"]));
            }
            set {
                this["QrCodeDetectorFormLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QrCodeDetectorFormLocationY {
            get {
                return ((int)(this["QrCodeDetectorFormLocationY"]));
            }
            set {
                this["QrCodeDetectorFormLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QrCodeDetectorFormWidth {
            get {
                return ((int)(this["QrCodeDetectorFormWidth"]));
            }
            set {
                this["QrCodeDetectorFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QrCodeDetectorFormHeight {
            get {
                return ((int)(this["QrCodeDetectorFormHeight"]));
            }
            set {
                this["QrCodeDetectorFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoAddFromWatchDirectory {
            get {
                return ((bool)(this["AutoAddFromWatchDirectory"]));
            }
            set {
                this["AutoAddFromWatchDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OnAdd")]
        public global::QrCodeDetector.QrCodeDetectorForm.AutoDetectOptions AutoDetectOption {
            get {
                return ((global::QrCodeDetector.QrCodeDetectorForm.AutoDetectOptions)(this["AutoDetectOption"]));
            }
            set {
                this["AutoDetectOption"] = value;
            }
        }
    }
}
